import { useEffect, useState } from "react";
import type { WorkspaceCommand, WorkspaceCommandExecution, WorkspaceCommandOutput } from "../../types/workspaceAnalysis";
import type { DashboardSummary } from "./DashboardTypes";

type DashboardWidgetsProps = { summary: DashboardSummary; onNavigate: (pageId: string) => void };
type InfoCardProps = { title: string; value: string; detail: string };

function InfoCard({ title, value, detail }: InfoCardProps) {
  return <article className="info-panel"><h3>{title}</h3><p>{value}</p><span>{detail}</span></article>;
}

function CommandRow({ label, command }: { label: string; command?: string }) {
  return <div><dt>{label}</dt><dd>{command ?? "Not available"}</dd></div>;
}

function WorkspaceCommandCard({ command, onCopy, onRun, copiedId, runningId }: { command: WorkspaceCommand; onCopy: (command: WorkspaceCommand) => void; onRun: (command: WorkspaceCommand) => void; copiedId?: string; runningId?: string }) {
  const blocked = command.permission === "blocked";
  const actionLabel = command.permission === "interactive" ? "Start" : command.permission === "device-changing" ? "Upload" : "Run";
  return (
    <article className="workspace-command-card">
      <div className="workspace-command-heading">
        <div><span className="workspace-command-category">{command.category}</span><h4>{command.label}</h4></div>
        <div className="workspace-command-actions"><button className="secondary-button workspace-command-copy" type="button" onClick={() => onCopy(command)}>{copiedId === command.id ? "Copied" : "Copy"}</button><button className="primary-button" type="button" disabled={Boolean(blocked || runningId)} title={blocked ? "This command remains copy-only because it was not generated by an approved executable profile." : undefined} onClick={() => onRun(command)}>{runningId === command.id ? "Running" : actionLabel}</button></div>
      </div>
      <code>{command.command}</code>
      <p>{command.description}</p>
      <div className="workspace-command-meta">
        <span>{command.source}</span>
        <span className={`command-permission command-permission-${command.permission}`}>{command.permission}</span>
        {command.workingDirectory && <span>cwd: {command.workingDirectory}</span>}
      </div>
    </article>
  );
}

export function DashboardWidgets({ summary, onNavigate }: DashboardWidgetsProps) {
  const [copiedId, setCopiedId] = useState<string>();
  const [execution, setExecution] = useState<WorkspaceCommandExecution>();
  const [output, setOutput] = useState<WorkspaceCommandOutput[]>([]);
  const [executionError, setExecutionError] = useState<string>();
  const enabledCapabilities = summary.capabilities.filter((capability) => capability.enabled);
  const disabledCapabilities = summary.capabilities.filter((capability) => !capability.enabled);
  const embedded = summary.workspaceAnalysis.embedded;
  const commands = summary.workspaceAnalysis.workspaceCommands;

  async function runCommand(command: WorkspaceCommand) {
    const bridge = window.workflowStudio?.workspace;
    if (!bridge?.runCommand) {
      setExecutionError("Native command execution bridge is unavailable.");
      return;
    }
    setOutput([]);
    setExecutionError(undefined);
    let approvedPermission: "interactive" | "device-changing" | undefined;
    if (command.permission === "device-changing") {
      const approved = window.confirm(`Upload firmware to the connected device?\n\n${command.command}\n\nKeep the device connected until the command finishes.`);
      if (!approved) return;
      approvedPermission = "device-changing";
    } else if (command.permission === "interactive") {
      const approved = window.confirm(`Start an interactive command session?\n\n${command.command}\n\nUse Stop in the command console to end the session.`);
      if (!approved) return;
      approvedPermission = "interactive";
    }
    try {
      const next = await bridge.runCommand(summary.rootPath, command.id, approvedPermission);
      setExecution(next);
    } catch (error) {
      setExecutionError(error instanceof Error ? error.message : String(error));
    }
  }

  async function cancelCommand() {
    if (!execution || !window.workflowStudio?.workspace?.cancelCommand) return;
    await window.workflowStudio.workspace.cancelCommand(execution.executionId);
    setExecution((current) => current ? { ...current, status: "cancelled" } : current);
  }

  useEffect(() => {
    const unsubscribe = window.workflowStudio?.workspace?.onCommandOutput?.((entry) => {
      setOutput((current) => current.length >= 500 ? [...current.slice(-450), entry] : [...current, entry]);
      if (entry.stream === "system" && /completed successfully|exited with code|Stopped by/.test(entry.text)) {
        setExecution((current) => current ? { ...current, status: entry.text.includes("completed successfully") ? "completed" : current.status === "cancelled" ? "cancelled" : "failed" } : current);
      }
    });
    return unsubscribe;
  }, []);

  async function copyCommand(command: WorkspaceCommand) {
    try {
      await navigator.clipboard.writeText(command.command);
      setCopiedId(command.id);
      window.setTimeout(() => setCopiedId((current) => current === command.id ? undefined : current), 2200);
    } catch (error) {
      console.warn("Unable to copy workspace command.", error);
    }
  }

  return (
    <>
      <section className="dashboard-quick-actions" aria-label="Dashboard quick actions">
        <div>
          <p className="eyebrow">Continue Working</p>
          <h3>{summary.currentMilestone}</h3>
          <p>Open the workspace you need without losing the current project context.</p>
        </div>
        <div className="dashboard-quick-action-buttons">
          <button type="button" className="primary-button" onClick={() => onNavigate("ai-workspace")}>Open AI Workspace</button>
          <button type="button" className="secondary-button" onClick={() => onNavigate("git")}>Review Git</button>
          <button type="button" className="secondary-button" onClick={() => onNavigate("packages")}>Open Packages</button>
        </div>
      </section>

      <section className="panel-grid dashboard-overview-cards">
        <InfoCard title="Project Readiness" value={`${summary.readinessScore}%`} detail={summary.readinessStatus} />
        <InfoCard title="Lifecycle" value={summary.lifecyclePhase} detail={summary.currentMilestone} />
        <InfoCard title="Project Type" value={summary.projectType} detail={`Toolchain: ${summary.packageManager}`} />
        <InfoCard title="Commands" value={`${commands.length}`} detail="Available workspace actions" />
      </section>

      <section className="dashboard-grid dashboard-intelligence-grid">
        <article className="detail-panel readiness-overview-panel">
          <div className="section-heading">
            <div><h3>Project Readiness</h3><p>Readiness is measured by project phase. Planned work does not count as a failure.</p></div>
            <span className={`lifecycle-badge lifecycle-${summary.lifecyclePhase.toLowerCase()}`}>{summary.lifecyclePhase}</span>
          </div>
          <div className="readiness-category-grid">
            {summary.readinessCategories.map((category) => (
              <article className={`readiness-category readiness-${category.status.toLowerCase().replaceAll(" ", "-")}`} key={category.id}>
                <div className="readiness-category-heading"><h4>{category.label}</h4><strong>{category.score === undefined ? category.status : `${category.score}%`}</strong></div>
                {category.score !== undefined && <div className="health-meter compact" aria-label={`${category.label} readiness ${category.score}%`}><div style={{ width: `${category.score}%` }} /></div>}
                <span>{category.status}</span><p>{category.detail}</p>
              </article>
            ))}
          </div>
        </article>

        {embedded?.detected && (
          <article className="detail-panel embedded-summary-panel">
            <div className="section-heading"><div><h3>Embedded Target</h3><p>Target details appear as firmware configuration is added.</p></div></div>
            <dl>
              <CommandRow label="Platform" command={embedded.platform ?? (summary.lifecyclePhase === "Planning" ? "Planned" : undefined)} />
              <CommandRow label="Board" command={embedded.boardIdentifiers.join(", ") || (summary.lifecyclePhase === "Planning" ? "Not selected yet" : undefined)} />
              <CommandRow label="Framework" command={embedded.frameworks.join(", ") || (summary.lifecyclePhase === "Planning" ? "Not selected yet" : undefined)} />
              <CommandRow label="Firmware" command={embedded.firmwareSourcePath ?? (summary.lifecyclePhase === "Planning" ? "Not started" : undefined)} />
              <CommandRow label="Device Profile" command={embedded.deviceProfile ?? "General embedded device"} />
            </dl>
          </article>
        )}

        <article className="detail-panel smart-recommendations-panel">
          <div className="section-heading">
            <div>
              <h3>Smart Recommendations</h3>
              <p>Prioritized from the current lifecycle, readiness, detected files, and workspace notices.</p>
            </div>
            <span className="recommendation-count">{summary.recommendations.length}</span>
          </div>
          <div className="smart-recommendation-list">
            {summary.recommendations.map((recommendation) => (
              <article className={`smart-recommendation recommendation-${recommendation.priority}`} key={recommendation.id}>
                <div className="smart-recommendation-heading">
                  <div>
                    <span className="recommendation-category">{recommendation.category}</span>
                    <h4>{recommendation.title}</h4>
                  </div>
                  <span className={`recommendation-priority priority-${recommendation.priority}`}>{recommendation.priority}</span>
                </div>
                <p>{recommendation.detail}</p>
                {recommendation.actionLabel && recommendation.targetPageId && (
                  <button
                    type="button"
                    className={recommendation.priority === "high" ? "primary-button" : "secondary-button"}
                    onClick={() => onNavigate(recommendation.targetPageId!)}
                  >
                    {recommendation.actionLabel}
                  </button>
                )}
              </article>
            ))}
          </div>
        </article>

        <article className="detail-panel workspace-commands-panel">
          <div className="section-heading"><div><h3>Workspace Commands</h3><p>Safe commands run directly. Interactive and device-changing commands require approval.</p></div></div>
          <div className="workspace-command-list">
            {commands.map((command) => <WorkspaceCommandCard key={command.id} command={command} onCopy={copyCommand} onRun={runCommand} copiedId={copiedId} runningId={execution?.status === "running" ? execution.commandId : undefined} />)}
          </div>
          {(execution || executionError || output.length > 0) && <section className="command-console" aria-live="polite"><div className="command-console-heading"><div><h4>Command Output</h4><p>{execution ? `${execution.label} — ${execution.status}` : executionError}</p></div>{execution?.status === "running" && <button className="secondary-button" type="button" onClick={cancelCommand}>Stop</button>}</div><pre>{output.map((entry, index) => <span className={`command-output-${entry.stream}`} key={`${entry.timestamp}-${index}`}>{entry.text}</span>)}</pre></section>}
        </article>

        <details className="detail-panel dashboard-details-panel">
          <summary>Capabilities and technical details</summary>
          <div className="dashboard-details-content">
            <section><h4>Enabled Capabilities</h4><div className="capability-list">{enabledCapabilities.map((capability) => <span className="capability-pill enabled" key={capability.id} title={capability.detail}>✓ {capability.label}</span>)}</div></section>
            <section><h4>Not Available Yet</h4><div className="capability-list">{disabledCapabilities.length > 0 ? disabledCapabilities.map((capability) => <span className="capability-pill disabled" key={capability.id} title={capability.detail}>• {capability.label}</span>) : <p className="empty-state">No unavailable capabilities.</p>}</div></section>
            <section><h4>Detected</h4><ul>{summary.healthSuccesses.map((success) => <li className="success-item" key={success}>{success}</li>)}</ul></section>
            <section><h4>Raw Analyzer Notices</h4><ul>{summary.healthWarnings.length > 0 ? summary.healthWarnings.map((warning) => <li className="warning-item" key={warning}>{warning}</li>) : <li className="success-item">No notices detected.</li>}</ul></section>
          </div>
        </details>
      </section>
    </>
  );
}
